spring:
  cloud:
    gateway:
      routes:
      - id: baidu-route
        uri: http://www.baidu.com
        predicates:
        - Query=url,baidu
      - id: qq-route
        uri: https://www.qq.com
        predicates:
        - Query=url,qq
      - id: admin-route
        uri: lb://renren-fast
        predicates:
          - Path=/api/**
        filters:
          - RewritePath=/api/(?<segment>.*), /renren-fast/$\{segment}
      - id: product_route
        uri: lb://mall-product
        predicates:
          - Path=/api/product/**
        filters:
          - RewritePath=/api/product/(?<segment>.*),/$\{segment}
## 前端项目都是/api
## http://localhost:8080/api/captcha   => http://localhost:8080/renren-fast/captcha.jpg?uuid=8c47a8ed-39d8-4d4b-8457-3b8f10a14abe
## http://localhost:88/api/product/category/list/tree => http://localhost:10001/mall-product/category/list/tree