spring:
  cloud:
    gateway:
      routes:
      - id: baidu-route
        uri: http://www.baidu.com
        predicates:
        - Query=url,baidu
      - id: qq-route
        uri: https://www.qq.com
        predicates:
        - Query=url,qq
